#!/bin/bash -x

DIR_NAME=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "${DIR_NAME}/common.sh"
check_command

function gather_validating_wh() {
  webhooks_collection_path=${BASE_COLLECTION_PATH}/webhooks/validating/${1}
  mkdir -p "${webhooks_collection_path}"

  /usr/bin/oc get validatingwebhookconfiguration "${1}" -o yaml | grep -vi cabundle > "${webhooks_collection_path}/validatingwebhookconfiguration.yaml"

  # fetch the service associated with webhook
  /usr/bin/oc get validatingwebhookconfiguration "${1}" -o=go-template --template='{{ range .webhooks }}-n {{.clientConfig.service.namespace}} {{.clientConfig.service.name}}{{ "\n" }}{{ end }}' | uniq | xargs /usr/bin/oc get service -o yaml > "${webhooks_collection_path}/service.yaml"
}

export -f gather_validating_wh

validating_wh=$(/usr/bin/oc get validatingwebhookconfiguration -o custom-columns=NAME:.metadata.name --no-headers | grep -i flowcollectorconversionwebhook)
echo "${validating_wh[@]}" | tr ' ' '\n' | xargs -t -I{}  --max-args=1 sh -c 'gather_validating_wh $1' -- {}


exit 0
