#!/bin/bash -x

DIR_NAME=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "${DIR_NAME}/common.sh"
check_command

CRD=$(/usr/bin/oc get crd | grep netobserv.io | awk '{print $1}')

# Run the collection of crds using must-gather
echo "${CRD[@]}" | tr ' ' '\n' | xargs -t -I{}  --max-args=1 sh -c '/usr/bin/oc adm inspect crd --dest-dir ${BASE_COLLECTION_PATH} $1' -- {}

exit 0
